### ISSUE TITLE
filepath.IsAbs() does not check for things like "/test/../test"

### ISSUE THREAD

**Issue by jakobvarmose** [ipfs-filestore/go-ipfs#13]
I'm not sure if this is a problem or not, but it might be.

It's used in many places, one of them here: https://github.com/ipfs-filestore/go-ipfs/blob/88c5d5dfa9af5a37eac067de5df8d4d012108399/filestore/datastore.go#L61

**Comment by kevina** [comment]
The only thing I care about in that case is if the path does not depend on the current directory.  I will actually end up storing a path with ".." in the filestore.  I also do not make any attempt to follow symbolic links.

On a side note it is actually incorrect to resolve ".." mechanically and I filed an issue to that effect golang/go#16255.
