### ISSUE TITLE
Error on WIndows for filestore add

### ISSUE THREAD

**Issue by jefft0** [ipfs-filestore/go-ipfs#6]
On Windows 8.1, I used Cygwin to `build install` the latest from branch kevina/filestore. In a Windows command prompt, I tried:

```
ipfs filestore add -r C:\cameras\2016
```

It says "File path must be absolute." In a Cygwin terminal, I also tried:

```
ipfs filestore add -r /cygdrive/c/cameras/2016
```

It says "The system cannot find the path specified."

**Comment by kevina** [comment]
Ok try checking out the `issue-6` branch and try again.  I think that should work for you.

**Comment by jefft0** [comment]
`ipfs filestore add -r C:\cameras\2016` works now. Thanks! I'll report results on the pull request when I have them.

**Comment by kevina** [comment]
Thanks.

@jefft0 Are you willing to try out some experimental code for me, I need some testing on some windows
specific code to address some path issues.

**Comment by jefft0** [comment]
Sure. Is Windows 8.1 enough, or do you need earlier Windows versions too?

**Comment by kevina** [comment]
Thanks.  Windows 8.1 is fine.  I opened a new issue #7.  The tests will be very simple.
