### ISSUE TITLE
Windows Testing

### ISSUE THREAD

**Issue by kevina** [ipfs-filestore/go-ipfs#7]
@jefft0 Let's discuss windows testing here.

**Comment by kevina** [comment]
@jefft0 please checkout the `windows` branch and try to build.  Then try to add a relative path with '-P' it should work for you.

**Comment by jefft0** [comment]
When I `make install` I get a build error:

```
c:\work\go\src\github.com\ipfs\go-ipfs\filestore\support\blockstore.go:71: undefined: filestore.CleanPath
```

(I don't get the error on the master or kevina/filestore branches.)

**Comment by kevina** [comment]
Oops.  Forgot to push a commit.  Please pull and try again.

This still may not even compile, so if you know any go it would be helpful if you can fix simple compile errors on your own.  :)

**Comment by kevina** [comment]
Note: Assuming you can compile the `windows` branch, that will be the best one to use for testing for now.  If you can't get it it to compile than `kevina/filestore` will also now work for you.

**Comment by jefft0** [comment]
I got another `make install` error. As you requested, I'll try to fix this and future errors myself. There will be a brief learning curve while I familiarize myself with the code. If you want to see the build error:

```
\ipfs\go-ipfs\merkledag\node.go:31: undefined: files.PosInfo
```

**Comment by kevina** [comment]
Hi @jefft0, my change should not have caused this problem.  You might want to make sure you have a clean checkout of the latest windows branch (4a55ff0f55ddb0c30c96e3bd62ca6c062d512727) and also try `make clean`.

Please don't hesitate to post build problems, while you work and try to fix them yourself.

**Comment by jefft0** [comment]
I blasted my local repo and started from a fresh `go get`. Now it builds. (Maybe `make clean` doesn't fully restore to a fresh state?) 

Anyway, `ipfs filestore add -P` and `ipfs filestore add -P -r` work as expected. I did a cd to c:\temp where there is a folder cameras. I did `ipfs filestore add -r -P cameras`. The file was added and when I run `ipfs daemon` it is served. `ipfs filestore ls' shows the absolute path C:/temp/cameras/camera3.20150705_020000.mp4.

**Comment by kevina** [comment]
Ok great and Thanks.  That is all the windows specific testing that I want to do for now.

I pushed the changes to `kevina/filestore` and will delete the windows branch shortly.  You should be using `kevina/filestore` for testing now.

**Comment by jefft0** [comment]
Initial stress-testing results: I have a subcollection of webcam videos, size 1.6 TB, on an external USB array. `filestore add -r` added them in 15 hours. `.ipfs\filestore-db` has 667 ldb files, total size 1.2 GB which seems reasonable. My total collection is about 10 times this size. We'll see how it goes.

**Comment by kevina** [comment]
Great!  Please report the final result as a comment to the initial pull request.

If you run into any problems please file a new issue to avoid unnecessary noise on the pull request.
