### ISSUE TITLE
Progress bar on folder of one file shows total "?"

### ISSUE THREAD

**Issue by jefft0** [ipfs-filestore/go-ipfs#9]
Possibly related to issue #8, I have a folder with one file of size 142.41 MB. I built the branch issue-6 on Windows 8.1 and did `ipfs filestore add -r c:\temp\cameras`. The file is added correctly, but the progress bar has a total of "?" and a random percentage.

```
142.41 MB / ? [--------------=----] 1493238.25% 2s
```

**Comment by kevina** [comment]
@jefft0 Does a normal add, for example `ipfs add -r c:\temp\cameras` give the same results?

**Comment by kevina** [comment]
Note I tried this myself and didn't get the '?'.

**Comment by jefft0** [comment]
`ipfs add` shows the correct total. BTW, are you going to merge branch issue-6 into branch windows (or kevina/filestore)? In other words, which branch should I be testing?

**Comment by jefft0** [comment]
I can't reproduce this error with the "?" total either. We can close this and focus on issue #8 .

**Comment by kevina** [comment]
> BTW, are you going to merge branch issue-6 into branch windows (or kevina/filestore)? In other words, which branch should I be testing?

I rebased the commit and it is now in kevina/filestore and windows.

I need your help even getting the "windows" branch to compile and run as I do 
not have easy access to a windows machine.  It will likely take several 
iterations so rapid feedback would be appeciated.

**Comment by jefft0** [comment]
I will attempt rapid feedback, given that I'm in the Barcelona time zone.

**Comment by kevina** [comment]
Thanks @jefft0, please let me know if you can get the `windows` branch to compile now at issue #7.
